### ISSUE TITLE
How to parse annotations

### ISSUE THREAD

**Issue by f3l1x** [mathiasverraes/parsica#11]
Hi! ✋  This library looks great and I would like to take a closer look.

Let's say I would like to practice on annotations. 

```
/**
* @foo Simple line
* @bar Advanced line with !@#$%^&*()
* @baz Multi line
*            with extra line
*/
```

Could you please point me how to start with it? :-) 

Thank you, Felix

**Comment by mathiasverraes** [comment]
I assume you've seen the docs at https://parsica.verraes.net/ ? Have a look
at the code as well, especially the /tests and the json example.

A good heuristic is to start from the inside.
Parse a text line, parse a @, parse a keyword, and then combine those.
For multilines, you could parse many whitespace * whitespace text line
combos.
Finally use between() for the outsides.

Does that help?

**Comment by bar** [comment]
@f3l1x OMG what did I do?

**Comment by f3l1x** [comment]
@mathiasverraes Thank you for pointing me. I was hoping for some more specific code example, but I can learn it from the tests.
