### ISSUE TITLE
Support for ABNF (Augmented Backus-Naur form)

### ISSUE THREAD

**Issue by akondas** [mathiasverraes/parsica#8]
It's just an idea to somehow support or parse things in accordance with the ABNF notation (https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form). At present, a lot of RFCs contain definitions that can be implemented in accordance with ABNF. One example:

Macro definition (from SPF [RFC7208](https://tools.ietf.org/html/rfc7208#section-7.1)):
```
The ABNF description for a macro is as follows:

   macro-string     = *( macro-expand / macro-literal )
   macro-expand     = ( "%{" macro-letter transformers *delimiter "}" )
                      / "%%" / "%_" / "%-"
   macro-literal    = %x21-24 / %x26-7E
                      ; visible characters except "%"
   macro-letter     = "s" / "l" / "o" / "d" / "i" / "p" / "h" /
                      "c" / "r" / "t" / "v"
   transformers     = *DIGIT [ "r" ]
   delimiter        = "." / "-" / "+" / "," / "/" / "_" / "="
```

At the moment, it would look more like this:

```php
$delimiters = optional(atLeastOne(oneOfS('-\.+,/_=')));
$transformers = optional(atLeastOne(digitChar()))->append((optional(string('r'))));
$macroLetter = oneOfS('slodiphcrtv');
$macroLiteral = atLeastOne(anySingleBut('%'));
$macroExpand = string('%{')->append($macroLetter)->append($transformers)->append($delimiters)->append(string('}'))
    ->or(string('%%'))->or(string('%_'))->or(string('%-'));
$macroString = many($macroExpand->or($macroLiteral));

// test with data
$macroString->run('%{lr-}.lp.%{ir}.%{v}._spf.%{d2}');
```

Of course, you can work it out manually now, but I leave this idea here. Thanks for this excellent library :clap:

**Comment by akondas** [comment]
In fact, one could write a project that parses this notation with the help of this project :thinking:

**Comment by mathiasverraes** [comment]
That would be pretty sweet indeed :-)

One way to do ABNF->parsica  (or at least make it easier) would be to have a ABNF namespace in Parsica with its own set of parsers and combinators that strictly follow ABNF terminology and meaning. 

Not a priority for me right now, too much other things to get to 1.0. But if you want to build this, I'd be happy to help or pair with you to get you started.
